version: "3"

services:
  chatgpt_uiweb:
    container_name: chatgpt_uiweb
    restart: always
    depends_on:
      - fast_api
    env_file:
      - .env
    ports:
      - '${CLIENT_PORT:-80}:80'
    volumes:
      - .:/app
    build:
      context: "."
      dockerfile: Dockerfile

  fast_api:
    container_name: azure_gpt
    build:
        context: "../webserver/."
    env_file:
      - .env
    restart: always
    ports:
      - 5174:5174

